import logging
from typing import List, Tuple, Optional
from app.agents.models import AgentStep
from app.agents.prompts import build_reflection_prompt
from app.agents.llm_gateway import LLMGateway

logger = logging.getLogger("unifound.agents.reflection")


class ReflectionAgent:
    """
    Validates candidate answers generated by the ReAct orchestrator before delivery to the user.
    Enforces truthfulness, consistency with observations, and accuracy regarding tool outcomes.
    """

    def __init__(self, llm_gateway: LLMGateway):
        self.gateway = llm_gateway

    async def validate(
        self,
        query: str,
        steps: List[AgentStep],
        candidate_answer: str,
    ) -> Tuple[bool, Optional[str], Optional[str]]:
        """
        Evaluate candidate answer.
        Returns:
            - is_valid (bool): Whether the response passed quality and factual verification.
            - feedback (str | None): Corrective feedback if verification failed.
            - refined_answer (str | None): An improved answer if minor refinement is suggested.
        """
        prompt = build_reflection_prompt(
            query=query,
            steps=steps,
            candidate_answer=candidate_answer,
        )

        is_valid, feedback, refined_answer = await self.gateway.reflect(
            prompt=prompt,
            steps=steps,
            candidate_answer=candidate_answer,
        )

        if not is_valid:
            logger.info("Reflection check rejected candidate answer: %s", feedback)
        else:
            logger.debug("Reflection check verified candidate answer successfully.")

        return is_valid, feedback, refined_answer
